services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: 1
      MYSQL_USER: 1
      MYSQL_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dognet
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   container_name: dogrestaurant-customers
  #   restart: always
  #   #environment:
  #     #- NODE_ENV=development
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src:/app/src
  #   networks:
  #     - dognet

volumes:
  mysql_data:

networks:
  dognet:
  

  