apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-restaurant-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dog-restaurant-customer
  template:
    metadata:
      labels:
        app: dog-restaurant-customer
    spec:
      hostname: dog-restaurant-customer
      serviceAccountName: dog-service-account
      containers:
      - name: dog-restaurant-customer
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/dog-restaurant-customer:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: AWS_REGION
          value: "us-east-1"   