apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-restaurant-customers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dog-restaurant-customers
  template:
    metadata:
      labels:
        app: dog-restaurant-customers
    spec:
      hostname: dog-restaurant-customers
      serviceAccountName: dog-service-account
      containers:
      - name: dog-restaurant-customers
        image: "${DOG_RESTAURANT_CUSTOMERS_IMAGE}"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: AWS_REGION
          value: "us-east-1"   
        - name: DB_NAME
          value: "${DB_NAME}"
        - name: DB_PORT
          value: "${DB_PORT}"    
        - name: DB_USER
          value: "${DB_USER}"     
        - name: DB_PASSWORD
          value: "${DB_PASSWORD}"
        - name: DB_HOST
          value: "${DB_HOST}"