apiVersion: v1
kind: Service
metadata:
  name: dog-restaurant-customer-elb
  namespace: default
spec:
  selector:
    app: dog-restaurant-customer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
